### PR TITLE
[i16] Support for namespace declarations

### PR DESCRIPTION
**Pull request by christiangalsterer**

### CODE REVIEW

**Comment by purbon** [comment]
nice work, thanks for your contribution, before we can move forward it would be required that you sign the CLA, see more details at https://www.elastic.co/contributor-agreement. Keep in mind to use the email you used while committing this PR, this is important for the internal checks.

looking forward to get this in.

**Comment by christiangalsterer** [comment]
I just submitted the CLA, so it should be there in a few minutes. Please let me know if you don't see it.

**Comment by christiangalsterer** [comment]
Please let me know if there is a problem with the CLA or if you need more information.

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
LGTM

**Pull request closed without merging**
