### PR TITLE
Pull request to add suppress_empty option to the xml filter plugin

### PR DESCRIPTION
**Pull request by ChrisMagnuson**
More details in the issue linked with this pull request.

### CODE REVIEW

**Comment by ChrisMagnuson** [comment]
I have now signed the CLA, not sure how to trigger this to try again.

**Comment by petrkalina** [comment]
Hello, this improvement would help us a lot. When might I expect the updated version to become available and when this happens - where will it be made available? thanks! peter

**Comment by spookerlabs** [comment]
Will this be available at 1.5 versions ? Having some issues with values being save as {} and kind of impossive gsub them =(!

**Comment by suyograo** [comment]
Fixed via https://github.com/logstash-plugins/logstash-filter-xml/pull/32

**Pull request closed without merging**
