### PR TITLE
Next features for formatting

### PR DESCRIPTION
**Pull request by wiibaa**
Waiting for #26 to be merged first!

This PR includes:
* Rewrite of logic proposed in #23 + rebase
* rewrite of logic proposed in #31 + tests
* breaking change, better default for handling "empty elements"

### CODE REVIEW

**Comment by suyograo** [comment]
@wiibaa merged #26

**Comment by suyograo** [comment]
@wiibaa this needs to go to both master and plugin-api-v1 branches. Can we do the breaking change only for master? So 2 PRs?

**Comment by wiibaa** [comment]
@suyograo yup I will need to handle the plugin-api-v1 in a separate PR, let's first review and finish this one.

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
